### ISSUE TITLE
Add filter functionality

### ISSUE THREAD

**Issue by shahednasser** [shahednasser/awesome-resources#385]
Add filter functionality where the emojis are buttons and on click only the items that have those emojis appear.

This is a tricky feature and can only be done through Jekyll

**Comment by blackbrokkoli** [comment]
Hi!

I attempted to solve this with purely Jekyll means, but I think that that would not only be very hard, but would also introduce a lot of complexity: Since the `index.html` is generated out of `README.md`, it would require splitting up the README with Jekyll filters, manually replacing the *Emojis Cheatsheet*. Now all changes would have to be pasted into two files. Then the list itself would have to be filtered with a custom Jekyll filter that searches and replaces list items - if a list item is incorrectly formatted, it may break `index.html` completely.

Considering these risks, I instead built this functionality with a simple and standalone javascript script, which is almost completely independent of all other files. I already created a [pull request](https://github.com/shahednasser/awesome-resources/pull/390).

Please let me know whether this works as you intended it.

**Comment by shahednasser** [comment]
Resolved in #390
